FROM golang:1.10

LABEL maintainer PlayNet <docker@play-net.org>
LABEL type "public"
LABEL versioning "simple"

ARG GIT_HOST
ARG REPO
ARG NAME
ARG COMMAND

ADD ./ /go/src/${GIT_HOST}/${REPO}/${NAME}
WORKDIR /go/src/${GIT_HOST}/${REPO}/${NAME}/

RUN make ${COMMAND}

CMD ["/bin/bash"]
